AuthUserFile    /home17/jepp/.config/proftpd/proftpd.passwd
AuthGroupFile   /home17/jepp/.config/proftpd/proftpd.group
AuthOrder       mod_auth_file.c
RequireValidShell off
ShowSymlinks on
DefaultChdir ~
AllowOverwrite on

<Limit PASV EPSV PORT EPRT TYPE MODE STRU PBSZ PROT>
  AllowAll
</Limit>

<Limit CWD XCWD CDUP XCUP>
  AllowAll
</Limit>

<Limit LIST NLST MLSD MLST READ RETR PWD>
  AllowAll
</Limit>

<Limit WRITE STOR STOU APPE DELE RNFR RNTO MKD RMD SITE_CHMOD SITE_CHGRP>
  AllowGroup testers
  DenyAll
</Limit>

<Directory /home17/jepp/donor_slots>
  <Limit CWD XCWD CDUP XCUP>
    DenyAll
  </Limit>
</Directory>